version: '2'
services:
  master:
    image: rickyking/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    environment:
      MASTER: spark://master:7077
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - data:/tmp/data
      - ./externalData:/externalData
  
  worker1:
    image: rickyking/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - master
    ports:
      - "8081:8081"
    volumes:
      - data:/tmp/data
      - ./externalData:/externalData
    depends_on:
      - master

  worker2:
    image: rickyking/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    links:
      - master
    ports:
      - "8082:8082"
    volumes:
      - data:/tmp/data
      - ./externalData:/externalData
    depends_on:
      - master
volumes:
  data: {}